version: '3.7'

services:
  database:
    container_name: postgresql
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    user: root
    volumes:
      - data:/var/lib/postgresql/data
  
volumes:
  data:
      

networks:
  default:
    external:
      name: home-automation
