version: '3.7'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
     - 80:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    init: true
    restart: always
    volumes:
      - ./home-assistant:/config
    environment: 
      - TZ=Europe/Amsterdam
    network_mode: host
    depends_on: 
      - node-red
      - mqtt
      - zigbee2mqtt
    
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    restart: always
    user: root
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./node-red:/data
    networks:
      - home-automation
    depends_on: 
      - mqtt
      - zigbee2mqtt
  

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    environment: 
      - TZ=Europe/Amsterdam
    volumes:
      - /run/udev:/run/udev:ro
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM:/dev/ttyACM
    privileged: true
    restart: always
    networks:
      - home-automation
    depends_on: 
     - mqtt

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto.conf
      - ./mqtt/passwd:/passwd
      - mqtt_data:/mosquitto/data
      - mqtt_data:/mosquitto/log
    networks:
      - home-automation

volumes:
  mqtt_data:

networks:
  home-automation:
    name: home-automation