version: '3.7'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports: 
      - 8000:8000
      - 9000:9000
    restart: always
    network_mode: bridge
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer
    depends_on: 
      - nginx
      - home-assistant
      - node-red
      - zigbee2mqtt
      - mqtt

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
     - 80:80
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - home-assistant
      - node-red
      - zigbee2mqtt
      - mqtt

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    init: true
    restart: always
    volumes:
      - ./home-assistant:/config
    environment: 
      - TZ=Europe/Amsterdam
    network_mode: host
    depends_on: 
      - node-red
      - zigbee2mqtt
      - mqtt
    
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    restart: always
    user: root
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./node-red:/data
    networks:
      - home-automation
    depends_on: 
      - zigbee2mqtt
      - mqtt
  

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    environment: 
      - TZ=Europe/Amsterdam
    volumes:
      - /run/udev:/run/udev:ro
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM:/dev/ttyACM
    privileged: true
    restart: always
    networks:
      - home-automation
    depends_on: 
     - mqtt

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto.conf
      - ./mqtt/passwd:/passwd
      - mqtt_data:/mosquitto/data
      - mqtt_data:/mosquitto/log
    networks:
      - home-automation

volumes:
  mqtt_data:
  portainer_data:

# networks:
#   home-automation:
#     name: home-automation