version: '3.7'

services:
  filebrowser:
    container_name: filebrowser
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: admin
        PASSWORD: admin
    ports:
     - 8080:80
    volumes:
     - /home/bas:/srv
    network_mode: bridge
    restart: no
