version: "3.7"

services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/config:/config
      - ./data/backups:/backups
      - /home/bas:/source
    ports:
      - 8200:8200
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200"]
      interval: 2m
      timeout: 15s
      retries: 3
      start_period: 10s
  
networks:
  default:
    external:
      name: home-automation