version: "2.1"

services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/config:/config
      - ./data/backups:/backups
      - /home/bas:/source
    ports:
      - 8200:8200
    restart: always
  
networks:
  default:
    external:
      name: home-automation