version: '3.7'

services:

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    restart: no
    volumes:
      - ./datag/mosquitto.conf:/mosquitto.conf
      - ./data/passwd:/passwd
      - data:/mosquitto/data
      - data:/mosquitto/log
    networks:
      - my-custom-network

volumes:
  data:

networks:
  my-custom-network:
    name: home-automation
    driver: bridge
