version: '3.7'

services:

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto.conf
      - ./passwd:/passwd
      - mqtt_data:/mosquitto/data
      - mqtt_data:/mosquitto/log
    networks:
      - home-automation

volumes:
  mqtt_data:

networks:
  home-automation:
    name: home-automation