homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  pasword: 25cI!@oppzHlHb28hbiky
  server: 'mqtt://mqtt'
  user: hass
permit_join: false
advanced:
  report: true
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d00046545e1':
    friendly_name: living_temperature
  '0x00158d00039fb096':
    friendly_name: lavalamp_socket
  '0x00158d000421de08':
    friendly_name: bedroom_temperature
  '0x0017880104316d1e':
    friendly_name: kitchen_light_table
  '0x90fd9ffffe299134':
    friendly_name: toilet_light
  '0x00178801047fe4ad':
    friendly_name: kitchen_light_sink
  '0x0017880104317f20':
    friendly_name: landing_light_stairwell
  '0x00178801047fe510':
    friendly_name: living_light_tv
  '0x00178801047fe50e':
    friendly_name: living_light_desk
  '0x00178801047fdfec':
    friendly_name: bedroom_closet
  '0x00178801043176cc':
    friendly_name: bedroom_window
  '0x000d6ffffe023a1f':
    friendly_name: '0x000d6ffffe023a1f'
groups:
  '1':
    friendly_name: kitchen_light_group
    devices:
      - 0x00178801047fe4ad/11
      - 0x0017880104316d1e/11
  '2':
    friendly_name: living_light_group
    devices:
      - 0x00178801047fe50e/11
      - 0x00178801047fe510/11
  '3':
    friendly_name: bedroom_light_group
    devices:
      - 0x00178801043176cc/11
      - 0x00178801047fdfec/11
  '4':
    friendly_name: all_rgb_light_group
    devices:
      - 0x0017880104316d1e/11
      - 0x00178801047fe4ad/11
      - 0x0017880104317f20/11
      - 0x00178801047fe510/11
      - 0x00178801047fe50e/11
      - 0x00178801047fdfec/11
      - 0x00178801043176cc/11
  '5':
    friendly_name: all_non-rgb_light_group
    devices:
      - 0x90fd9ffffe299134/11