version: '3.7'

services:
  wetty:
    image: svenihoney/wetty
    container_name: wetty
    environment:
      - REMOTE_SSH_SERVER=172.17.0.1   # needs to be the ip address of the docker host
      - REMOTE_SSH_PORT=22
      - REMOTE_SSH_USER=bas
    restart: always
    ports:
      - 3000:3000
      
networks:
  default:
    external:
      name: home-automation