version: '3.7'

services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    init: true
    restart: always
    volumes:
      - ./data:/config
    environment: 
      - TZ=Europe/Amsterdam
    network_mode: host
