version: '3.7'

services:
  code-server:
    image: linuxserver/code-server
    container_name: vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PASSWORD=admin #optional
      - SUDO_PASSWORD=admin #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./data:/config
    ports:
      - 8443:8443
    restart: "no"