version: '3.7'

services:
  code-server:
    image: linuxserver/code-server
    container_name: vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${PASSWORD}
    volumes:
      - ./data:/config
      - /home/bas/:/mnt/
    ports:
      - 8443:8443
    restart: "no"