version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
     - 80:80
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     restart: unless-stopped