version: '3.7'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports: 
      - 9000:9000
    restart: unless-stopped
    network_mode: bridge
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: